version: "3.3"

services:
  app:
    container_name: srcbot
    build: .
    command: gunicorn app:app & python3 main.py
    environment:
      API_ID: # Your API HASH from my.telegram.org
      API_HASH: # Your API ID from my.telegram.org
      BOT_TOKEN: # Bot token, get it from @BotFather
